on:
  pull_request:
  push:


jobs:
  kernel:
    runs-on: local/aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - name: set home
        run: |
          echo "HOME=$PWD" >> "$GITHUB_ENV"

      - name: build all
        run: |
          OUTPUT=$(nix build --print-out-paths --keep-going .#linux_jhovold .#linux_steev .#x13s/alsa-ucm-conf .#pd-mapper .#x13s/extra-firmware)
          echo $OUTPUT
          echo "$OUTPUT" > build.out

      - name: upload to cachix
        run: |
          cachix push nixos-x13s $(cat build.out)
        env:
          CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_TOKEN_X13S }}'

      - name: upload to attic
        run: |
          attic login --set-default $ATTIC_CACHE $ATTIC_ENDPOINT $ATTIC_TOKEN
          attic use $ATTIC_CACHE
          attic push $ATTIC_CACHE $(cat build.out)
        env:
          ATTIC_ENDPOINT: ${{ vars.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ vars.ATTIC_CACHE }}
          ATTIC_TOKEN: ${{ secrets.ATTIC_KEY }}
