on:
  pull_request:
  push:


jobs:
  kernel:
    runs-on: local/aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - name: set home
        run: |
          echo "HOME=$PWD" >> "$GITHUB_ENV"

      - name: build all
        run: |
          set -x
          TARGETS=$(nix eval .#packages.aarch64-linux --apply 'builtins.attrNames' --json | jq '. | map(".#" + .) | join(" ")' -r)
          OUTPUT=$(nix build --print-out-paths --keep-going $TARGETS)
          echo $OUTPUT
          echo "$OUTPUT" > build.out

      - name: upload to cachix
        run: |
          cachix push nixos-x13s $(cat build.out)
        env:
          CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_TOKEN_X13S }}'
