labels:
  type: local
  system: aarch64-linux

steps:
  - name: find-targets
    image: bash
    commands:
      - nix develop .#ci -c just -- find-targets

  - name: build
    image: bash
    commands:
      - nix develop .#ci -c just -- build

  - name: upload
    image: bash
    commands:
      - nix develop .#ci -c just -- push
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN

when:
  - event: push
